// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC3Y00LH7tguPILhDaG9LICr8FMSBJTPA',
    appId: '1:1072725472205:web:a364124876daa457f60a84',
    messagingSenderId: '1072725472205',
    projectId: 'weather-app-fe51e',
    authDomain: 'weather-app-fe51e.firebaseapp.com',
    storageBucket: 'weather-app-fe51e.appspot.com',
    measurementId: 'G-9Q2W6GQRMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjUv0dmUvMZGgvW3QRtDq-k5VIq-M2xW4',
    appId: '1:1072725472205:android:38f4a2356459733af60a84',
    messagingSenderId: '1072725472205',
    projectId: 'weather-app-fe51e',
    storageBucket: 'weather-app-fe51e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuYS4_VxJmJqqEoty2JRn42Xh6-83lzcE',
    appId: '1:1072725472205:ios:aae795b5a5cefdbaf60a84',
    messagingSenderId: '1072725472205',
    projectId: 'weather-app-fe51e',
    storageBucket: 'weather-app-fe51e.appspot.com',
    iosBundleId: 'com.developers.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuYS4_VxJmJqqEoty2JRn42Xh6-83lzcE',
    appId: '1:1072725472205:ios:e6dce1e687192e05f60a84',
    messagingSenderId: '1072725472205',
    projectId: 'weather-app-fe51e',
    storageBucket: 'weather-app-fe51e.appspot.com',
    iosBundleId: 'com.developers.weatherApp.RunnerTests',
  );
}
